### ISSUE TITLE
need to fix the cli execution permissions for normal users

### ISSUE THREAD

**Issue by chronical** [CloudSlang/cloudslang-cli#13]
Running the cslang cli requires superuser permission because of the logging log4j write permission

Need a way to enable acces to the cslang cli for any type of user

[x@ /]$ cslang
Loading..
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /usr/lib/node_modules/cloudslang-cli/cloudslang-cli/cslang-cli/logs/execution.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)

- running with elevated privileges (sudo cslang) works as expected.

**Comment by StefanCristian** [comment]
@chronical should it be normal to have superuser permission?

I'd propose using a secure location in the system with the current user, rather than elevated privileges.
